# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Annie Yang
tagline:             'A Brain Dump'
description:         'Hello hello! I'm Annie. Fan of maps, naps, and data viz. Two of these you'll find here. Tryna figure out what the heck is a data science.'
url:                 'http://ayang861.github.io'
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
